#ifndef BITMAPS_H
#define BITMAPS_H

extern const unsigned int CLEAR_16X16 [];

extern const unsigned int LEFT_HERO_1 [];

extern const unsigned int LEFT_HERO_2 [];

extern const unsigned int RIGHT_HERO_1 [];

extern const unsigned int RIGHT_HERO_2 [];

extern const unsigned int LEFT_HERO_JUMP [];

extern const unsigned int LEFT_HERO_FALL [];

extern const unsigned int RIGHT_HERO_JUMP [];

extern const unsigned int RIGHT_HERO_FALL []; 

extern const unsigned long CLEAR_32X32 [];

extern const unsigned long SAWBLADE [];

extern const unsigned long HEARTS_3 [];

extern const unsigned long HEARTS_2 [];

extern const unsigned long HEARTS_1 [];

extern const unsigned char PLATFORM_NORMAL [];

extern const unsigned char LEFT_PLATFORM_EDGE [];

extern const unsigned char RIGHT_PLATFORM_EDGE [];

extern const unsigned int SELECTION_ARROW [];

extern const unsigned int EXITDOOR [];

#endif